<?php print $this->fetch('home/pages/nav.phtml')?>
<div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">欢迎使用简·记云笔记</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>

        <!-- /.row -->
	<section id="aboutUs" class="page-section pDark pdingBtm30">
	<div class="container">
	    <div class="heading text-center" style="margin-left: -150px;">
			<!-- Heading -->
			<h2>关于 我们</h2>								 
			<p>云笔记是一款跨平台的简单快速的个人记事备忘工具，操作界面  
			简洁高效。例如：
			</p>
		</div>
	
		<div class="row" style="margin-left: 100px;">
			<div class="col-md-3 col-sm-6">	
	            <div class="tray text-center">											
					<h3><i class="fa fa-desktop color"></i> &nbsp;网页版操作</h3>
					<!-- Paragraph -->
					<p>电脑版操作，界面简洁，使用方便，实时保存，防止文件丢失。支持上传文件，分享文件等功能。</p>										
				</div>
            </div>
			<div class="col-md-3 col-sm-6">	
		        <div class="tray text-center">											
					<!-- Heading -->
					<h3><i class="fa fa-cloud color"></i> &nbsp;云端存储</h3>
					<!-- Paragraph -->
					<p>拥有云端同步功能，可直接创建新笔记。通过登录云笔记网站可直接编辑个人记事，实现协同操作。</p> 										
				</div>
            </div>
            <div class="col-md-3 col-sm-6">	
		        <div class="tray text-center">											
					<!-- Heading -->
					<h3><i class="fa fa-cloud color"></i> &nbsp;分享文件</h3>
					<!-- Paragraph -->
					<p>支持分享文件，可通过微信、QQ、微博等多种渠道进行分享。支持下载到本地，发送到手机。</p> 										
				</div>
            </div>
		</div>
	<!--/.container-->
	</section>
</div>