<?php print $this->fetch('home/pages/nav.phtml')?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <!-- <h1 class="page-header">欢迎使用简·记云笔记</h1> -->
            <input type="text" name="title" id="title" style="width: 100%;height: 40px;font-size: 18px;margin-top: 40px;" placeholder="&nbsp;简·记">
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- 插入编辑器 -->
    <div id="editor">
       
    </div>

    <!-- 注意， 只需要引用 JS，无需引用任何 CSS ！！！-->
    <script type="text/javascript" src="/wangEditor-3.1.1/release/wangEditor.min.js"></script>
    <script type="text/javascript">
        var E = window.wangEditor
        var editor = new E(document.getElementById('editor'))
        // 或者 var editor = new E( document.getElementById('editor') )
        editor.create()
    </script>
    <!-- 插入编辑器 -->
    <!--  <div class="ccc" style="width: 6%;height: 100%;border: none;color: #FFFFFF;font-size: 16px;background: #1A94E6;cursor: pointer;text-align: center;padding-top: 6px;margin-top: 6px;float: right;">保存</div> -->
    <button id="ccc" type="submit" class="btn btn-default" style="float: right;background: #4876FF;margin-top: 6px;color: #FFFFFF;">保存</button>
</div>
<script>
    $('#ccc').click(function(){
        alert('a');
        $.ajax({
            type:'post',
            url:'/donewnote',
            dataType:'text',
            data:{
                title:$('#title').val(),
                note:$('#editor').find('p').text(),
            },
            success:function(data){
                console.log(data);
                eval(data);
//                location.href = 'http://127.0.0.1:86';
            },
            error:function(err){
                alert('b');
                console.log(err)
            }
        });
    });
</script>