<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>简·记 云笔记</title>

    <link rel="stylesheet" href="/css/home/bootstrap.min.css" />     
<link rel="stylesheet" type="text/css" href="/css/home/isotope.css" media="screen" />   
<link rel="stylesheet" href="/js/fancybox/jquery.fancybox.css" type="text/css" media="screen" />
<link rel="stylesheet" type="text/css" href="/css/home/da-slider.css" />
<link rel="stylesheet" href="/css/home/styles.css"/>
<link rel="stylesheet" href="/css/home/self.css"/>


    <!-- Bootstrap Core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/vendor/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <script  src="/js/jquery-3.3.1.min.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!-- [if lt IE 9] -->
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <!-- [endif] -->

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">简·记 云笔记</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-messages">
                    <li>
                        <a href="#">
                            <div>
                                <strong>John Smith</strong>
                                <span class="pull-right text-muted">
                                        <em>昨天</em>
                                    </span>
                            </div>
                            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text-center" href="#">
                            <strong>查看所有信息</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
                <!-- /.dropdown-messages -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                    <li>
                        <a href="#">
                            <div>
                                <i class="fa fa-comment fa-fw"></i> New Comment
                                <span class="pull-right text-muted small">4分钟之前</span>
                            </div>
                        </a>
                    </li>
                    <li class="divider"></li>
                    
                    <li>
                        <a class="text-center" href="#">
                            <strong>See All Alerts</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
                <!-- /.dropdown-alerts -->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <?php 
                        if (empty($_SESSION['username'])) {
                            # code...
                            echo '<li><a href="#"><i class="fa fa-user fa-fw"></i> 用户中心</a></li>
                            <li class="divider"></li>
                            <li><a href="#"><i class="fa fa-gear fa-fw"></i> 用户设置</a></li>';
                        }else{
                             echo "<li style='margin-top:5px;margin-bottom:-10px;'><a href='#><i class='fa fa-user fa-fw'></i>hello,{$_SESSION['username']} </a></li>
                             <hr>
                            <li style='margin-top:-10px;'><a href='#'><i class='fa fa-gear fa-fw'></i> 用户设置</a></li>
                            <li class='divider'></li>
                            <li><a href='/logout'><i class='fa fa-sign-out fa-fw'></i> 退出登录</a></li>";
                        }
                    ?>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="搜索">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> 新建笔记<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="/newnote">新建笔记</a>
                            </li>
                            <li>
                                <a href="/newfile">新建文件夹</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> 导入<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="flot.html">导入文件</a>
                            </li>
                            <li>
                                <a href="morris.html">导入文件夹</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level
                    <!-- </li> --> 
                    <li>
                        <a href="#"><i class="fa fa-wrench fa-fw"></i> 我的文件夹<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="#">我的资源<span class="fa arrow"></span></a>
                                <?php
                                    if(!empty($_SESSION['username'])){
                                        foreach($result1 as $results){
                                            $id=$results['id'];
                                            $fname=$results['f_name'];
                                            $pre_fid=$results['pre_fid'];
                                            echo '<ul class="nav nav-third-level"><li>';
                                            if($pre_fid=='pre_fid'){
                                                 echo "<a href='/mynoteindex/{$results['id']}'>";
                                                echo $fname;
                                                echo '<span class="fa arrow"></span></a>';
                                            }
                                            foreach($result1 as $val){
                                                echo '<ul class="nav nav-fourth-level"><li>';
                                                if($results['id']==$val['pre_fid']){
                                                    echo "<a href='/mynoteindex/{$val['id']}''>";
                                                    echo $val['f_name'];
                                                    echo '<span class="fa arrow"></span></a>';
                                                }
                                                echo '</li></ul>';
                                            }
                                            echo '</li></ul>';
                                        }
                                    }
                                ?>
                    
                            </li>
                            <!-- <li>
                                <a href="/button">我的文档</a>
                            </li> -->
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="/noterecycle"><i class="fa fa-edit fa-fw"></i> 回收站</a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

   
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->
<div id="page-wrapper">
    <div class="row">
    <div>
           
              <?php foreach ($recyclenote as $val): ?>
                <div class="recycle">
					<div class="recycle1"><h4 style="padding-top:25px;"><?=$val['title']?></h4></div>
					<div class="recycle2"><p><?=$val['content']?></p></div>
					<div class="recycle3">
						<a href="/rebackrecycle/<?=$val['id']?>" title="恢复"><span class="glyphicon glyphicon-repeat" aria-hidden="true"></a>
						<a href="/noterecycle/delete/<?=$val['id']?>" title="永久删除"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
					</div>
                </div>
			  <?php endforeach; ?>
			  <?php 
                        echo '<div id="page" style="float:right;">';
                        echo $recyclenote->links('pagination/page.phtml');
                        echo '</div>';                   
                   ?>
            
        </div>
    </div>
</div>

</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="/vendor/jquery/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/vendor/bootstrap/js/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="/vendor/metisMenu/metisMenu.min.js"></script>

<!-- Morris Charts JavaScript -->
<script src="/vendor/raphael/raphael.min.js"></script>
<script src="/vendor/morrisjs/morris.min.js"></script>
<script src="/data/morris-data.js"></script>

<!-- Custom Theme JavaScript -->
<script src="/dist/js/sb-admin-2.js"></script>

</body>

</html>
