<!DOCTYPE html>
<html>
    <head>
		<meta charset="utf-8">
		<title>后台登录界面</title>
		<link rel="stylesheet" href="/css/admin/reset.css" />
		<link rel="stylesheet" href="/css/admin/common.css" />
		<link rel="stylesheet" href="/css/admin/font-awesome.min.css" />
	</head>
	<body background="water.jpg">
		<div class="wrap login_wrap">
			<div class="content">
				<div class="logo"></div>
				<div class="login_box">	
					
					<div class="login_form">
						<div class="login_title">
							后台登录
						</div>
						<form action="/admin/dologin" method="post">
							
							<div class="form_text_ipt">
								<input name="username" type="text" placeholder="用户名">
							</div>
							<span class="ececk_warning">用户名不能为空</span>
							<div class="form_text_ipt">
								<input name="password" type="password" placeholder="密码">
							</div>
							<div class="ececk_warning"><span>密码不能为空</span></div>
							<div class="form_check_ipt">
								<div class="left check_left">
									<label><input name="" type="checkbox"> 下次自动登录</label>
								</div>
								<div class="right check_right">
									<a href="#">忘记密码</a>
								</div>
							</div>
							<div class="form_btn">
								<input type="submit" style="width: 100%;height: 86%;border: none;color: #FFFFFF;font-size: 18px;background: #1A94E6;cursor: pointer;text-align: center;padding-top: 8px" tabindex="3" value="登录" class="btn btn-primary" />
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

</body>
</html>
