<?php print $this->fetch('admin/nav.phtml')?>
<div class="span10 content-right">
    <div class="container-fluid">
        <div class="row-fluid">
            <h4>数据列表</h4>
            <div class="w">
                <div class="span12">
                    <table class="table table-condensed table-bordered table-hover tab">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>作者</th>
                                <th>文档名称</th>
                                <th>创建时间</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <?php foreach($data['note'] as $results): ?>
                        <tr>
                            <td><?=$results['id'] ?></td>
                            <td><?=$results['author']?></td>
                            <td><?=$results['title']?></td>
                            <td><?=$results['create_time']?></td>
                            <td>
                                <a href="/admin/showMynote/<?=$results['id']?>">查看</a>
                                <a href="/mynote/delete/<?=$results['id']?>" onclick="javascript:return del();">删除</a>
                            </td>
                        </tr>
<?php endforeach;?>
                        
                        <tbody id="tbody"></tbody>
                    </table>

                  <?php 
                        echo '<div id="page" class="tr">';
                        echo $note->links('pagination/page.phtml');
                        echo '</div>';                   
                   ?>
            </div>
                </div>
                
            </div>
        </div>
    </div>
</div>


    

