<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet">
    <link href="/css/admin/bootstrap.min.css" rel="stylesheet" />
    <title></title>
    <link href="/css/admin/Comon.css" rel="stylesheet" />
    <link href="/css/admin/Index.css" rel="stylesheet" />
    <link href="/css/admin/Index2.css" rel="stylesheet" />
    <script type="text/javascript" src="/js/index.js"></script>
</head>
<body>
    <div class="header">

        <img class="logo" src="/images/logo.png" />
        <label class="logo-title">后台管理系统</label>
        <ul class="inline">
            <li><a class="loginout" href="/home/index">前台访问</a></li>
            <li>
                <img src="/images/32/client.png" />&nbsp;&nbsp;欢迎您,
                <?php 
                    echo $_SESSION['username'];
                ?>
            </li>
         
            <li>
                <img src="/images/32/200.png" />&nbsp;&nbsp;<a class="loginout" href="/admin/loginout" onClick="if(!confirm('是否确认退出？'))return false;">退出</a>
            </li>

        </ul>


    </div>
<div class="nav">

        <ul class="breadcrumb">
            <li>
                <img src="/images/32/5025_networking.png" />
            </li>
            <li><a href="/admin/index">首页</a> <span class="divider">>></span></li>
            <li class="active"></li>
        </ul>
    </div>
    <div class="container-fluid content">
        <div class="row-fluid">
            <div class="span2 content-left">
                <div class="accordion">
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                                <img class="left-icon" src="/images/32/5026_settings.png" /><span class="left-title">系统设置</span>
                            </a>
                        </div>
                        <div id="collapseOne" class="accordion-body collapse in">
                            <div class="accordion-inner">
                                <img class="left-icon-child" src="/images/32/4962_sitemap.png" /><span class="left-body"> 模块管理</span>
                            </div>
                            <div class="accordion-inner">
                                <img class="left-icon-child" src="/images/32/4957_customers.png" /><span class="left-body"> <a href="/admin/mynote">文档管理</a></span>

                            </div>
                            <div class="accordion-inner">
                                <img class="left-icon-child" src="/images/32/4992_user.png" /><span class="left-body"><a href="/admin/user"> 用户管理</a></span>

                            </div>
                            <div class="accordion-inner">
                                <img class="left-icon-child" src="/images/32/612.png" /><span class="left-body"> <a href="/admin/share">分享文档管理</a></span>

                            </div>
                            <div class="accordion-inner">
                                <img class="left-icon-child" src="/images/32/8.png" /><span class="left-body"><a href="/admin/recycle"> 回收站管理</a></span>

                            </div>
                        </div>
                    </div>
                </div>

            </div>

            
    
</body>
</html>
